export enum JoinStatus {
  // 참여
  RESERVED = 'RESERVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',

  // 미참여
  NOT_JOINED = 'NOT_JOINED',
  NOT_JOINABLE = 'NOT_JOINABLE',
}

export enum GroupStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}
